import React, { useState } from 'react';
import { Cpu, Save, Sliders, CheckCircle2, ShieldCheck, Zap } from 'lucide-react';

export const HardwareConfigurator: React.FC = () => {
  const [armBoost, setArmBoost] = useState(true);
  const [enableUart, setEnableUart] = useState(true);
  const [enableVc4Gpu, setEnableVc4Gpu] = useState(true);
  const [enableAudio, setEnableAudio] = useState(true);
  const [saved, setSaved] = useState(false);

  const configTxtContent = `# NexuzPi OS - Raspberry Pi 5 (BCM2712) config.txt
# Generated by Metanexuz.de / Nexuzcode.de Firmware Builder

arm_64bit=1
kernel=kernel_2712.img
initramfs initramfs.cpio.gz followkernel

# Hardware & Interfaces
enable_uart=${enableUart ? '1' : '0'}
dtparam=audio=${enableAudio ? 'on' : 'off'}

# VideoCore VII (VC4-KMS-V3D) GPU Acceleration
${enableVc4Gpu ? 'dtoverlay=vc4-kms-v3d\nmax_framebuffers=2' : '# GPU Overlays deaktiviert'}

# RPi 5 Performance Boost (Cortex-A76 @ 2.4GHz)
arm_boost=${armBoost ? '1' : '0'}
`;

  const cmdlineTxtContent = `console=serial0,115200 console=tty1 root=/dev/mmcblk0p2 rootwait rw quiet spidev.bufsiz=65536`;

  const handleSaveConfig = () => {
    setSaved(true);
    setTimeout(() => setSaved(false), 2500);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner */}
      <div className="p-6 rounded-2xl bg-slate-950 border border-fuchsia-900/40 shadow-xl flex flex-col md:flex-row items-start md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <Cpu className="w-6 h-6 text-fuchsia-400" />
            <h2 className="text-lg font-bold font-mono text-slate-100">
              Raspberry Pi 5 (BCM2712) Firmware & Kernel Konfiguration
            </h2>
          </div>
          <p className="text-xs text-slate-400 mt-1 max-w-2xl font-sans">
            Feinabstimmung für das Broadcom BCM2712 SoC (4x Cortex-A76 @ 2.4 GHz) mit VideoCore VII GPU Treibern für die NexuzPi OS Distribution.
          </p>
        </div>

        <button
          onClick={handleSaveConfig}
          className="flex items-center gap-2 px-5 py-2.5 rounded-xl font-mono text-xs font-bold bg-fuchsia-500 hover:bg-fuchsia-400 text-slate-950 shadow-[0_0_15px_rgba(217,70,239,0.3)] transition-all"
        >
          <Save className="w-4 h-4" />
          <span>{saved ? 'In /boot/config.txt Gespeichert!' : 'Einstellungen Speichern'}</span>
        </button>
      </div>

      {/* Hardware Toggles Grid */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          {
            title: 'ARM Boost (2.4 GHz)',
            desc: 'Maximale CPU Taktfrequenz für BCM2712 Cortex-A76',
            state: armBoost,
            toggle: () => setArmBoost(!armBoost)
          },
          {
            title: 'UART Serial Console',
            desc: 'Serielle Debug-Schnittstelle über GPIO Pins',
            state: enableUart,
            toggle: () => setEnableUart(!enableUart)
          },
          {
            title: 'VideoCore VII GPU (VC4)',
            desc: 'KMS-V3D Hardware 3D-Grafikbeschleunigung',
            state: enableVc4Gpu,
            toggle: () => setEnableVc4Gpu(!enableVc4Gpu)
          },
          {
            title: 'HD Audio Output',
            desc: 'I2S & HDMI Audio-Schnittstelle aktivieren',
            state: enableAudio,
            toggle: () => setEnableAudio(!enableAudio)
          }
        ].map(item => (
          <div
            key={item.title}
            onClick={item.toggle}
            className={`p-4 rounded-xl border cursor-pointer transition-all ${
              item.state
                ? 'bg-fuchsia-950/30 border-fuchsia-400/80 shadow-[0_0_10px_rgba(217,70,239,0.1)]'
                : 'bg-slate-900/50 border-slate-800 opacity-60'
            }`}
          >
            <div className="flex items-center justify-between">
              <span className="font-mono text-xs font-bold text-slate-200">{item.title}</span>
              <div className={`w-8 h-4 rounded-full p-0.5 transition-colors ${item.state ? 'bg-fuchsia-500' : 'bg-slate-700'}`}>
                <div className={`w-3 h-3 rounded-full bg-slate-950 transition-transform ${item.state ? 'translate-x-4' : 'translate-x-0'}`} />
              </div>
            </div>
            <p className="text-[11px] text-slate-400 mt-2 font-sans">{item.desc}</p>
          </div>
        ))}
      </div>

      {/* Generated config.txt and cmdline.txt preview */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* config.txt */}
        <div className="p-5 rounded-2xl bg-slate-950 border border-slate-800 shadow-xl">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2 mb-3">
            <span className="font-mono text-xs font-bold text-slate-200">
              Generierte /boot/config.txt
            </span>
            <span className="text-[10px] font-mono text-fuchsia-400">BCM2712 Bootloader</span>
          </div>
          <pre className="p-3 rounded-xl bg-slate-900/90 font-mono text-xs text-slate-200 overflow-x-auto leading-relaxed border border-slate-800">
            {configTxtContent}
          </pre>
        </div>

        {/* cmdline.txt */}
        <div className="p-5 rounded-2xl bg-slate-950 border border-slate-800 shadow-xl">
          <div className="flex items-center justify-between border-b border-slate-800 pb-2 mb-3">
            <span className="font-mono text-xs font-bold text-slate-200">
              Kernel Parameters /boot/cmdline.txt
            </span>
            <span className="text-[10px] font-mono text-cyan-400">ARM64 Kernel Args</span>
          </div>
          <pre className="p-3 rounded-xl bg-slate-900/90 font-mono text-xs text-slate-200 overflow-x-auto leading-relaxed border border-slate-800">
            {cmdlineTxtContent}
          </pre>
        </div>
      </div>
    </div>
  );
};
